## Module 6 Challenge
### Doris B. Cohen, April 2020 -------> Part 2

Part 2 Instructions 

Have Customers Narrow Their Travel Searches Based on Temperature and Precipitation To complete this task, follow these steps:

1. Create a new Jupyter Notebook file and name it Vacation_Search.ipynb.
2. Import the WeatherPy_vacation.csv file from Part 1 as a new DataFrame.
3. Filter the DataFrame for minimum and maximum temperature preferences, and if the rain or snow accumulation is 0 inches or not using conditional statements. Do the following: 
    Prompt the customer for the minimum temperature preference. 
    Prompt the customer for the maximum temperature preference. 
    Prompt the customer to answer if he or she would like it to be raining or not, using input("Do you want it to be raining? (yes/no) "). 
    Prompt the customer to answer if he or she would like it to be snowing or not, using input("Do you want it to be snowing? (yes/no) ").
4. Add the cities to a marker layer map with a pop-up marker for each city that includes: 
    Hotel name 
    City Country 
    Current weather description with the maximum temperature
5. Save and upload the new DataFrame as WeatherPy_vacation.csv.
6. Save and upload the new marker layer map as WeatherPy_vacation_map.png.

In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
import scipy
import timeit
import requests

# Import the commands and config info
import citipy
from citipy import citipy

from scipy import stats
from scipy.stats import linregress
#from config import weather_api_key
from datetime import datetime

In [2]:
# Read file from Part 1
city_vacay_df = pd.read_csv("weather_data/WeatherPy.csv")
city_vacay_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
0,0,Ustye,RU,2020-04-19 19:35:51,59.63,39.74,31.59,94,8,3.15,clear sky,0.0,0.0
1,1,Nyaunglebin,MM,2020-04-19 19:35:51,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0
2,2,Verkhoyansk,RU,2020-04-19 19:35:51,67.54,133.38,6.30,88,99,5.55,overcast clouds,0.0,0.0
3,3,Mataura,NZ,2020-04-19 19:35:52,-46.19,168.86,44.01,80,95,5.99,overcast clouds,0.0,0.0
4,4,Rikitea,PF,2020-04-19 19:35:52,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0

In [3]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 110

In [4]:
# Find out if the vacationer is okay with rain
rain = input("Do you want it to be raining? (yes/no) ")

Do you want it to be raining? (yes/no) no

In [5]:
# Find out if the vacationer is okay with snow
snow = input("Do you want it to be snowing? (yes/no) ")

Do you want it to be snowing? (yes/no) no

In [6]:
# Match criteria to answers
if rain == "no" and snow == "no":
    answer_filter_df = city_vacay_df.loc[(city_vacay_df["Max Temp"]<= max_temp) &
                                    (city_vacay_df["Max Temp"] >= min_temp) &
                                    (city_vacay_df["Rain/Inches"] == 0) &
                                    (city_vacay_df["Snow"] == 0)]

elif rain == "no" and snow == "yes":
    answer_filter_df = city_vacay_df.loc[(city_vacay_df["Max Temp"]<= max_temp) &
                                    (city_vacay_df["Max Temp"] >= min_temp) &
                                    (city_vacay_df["Rain/Inches"] == 0) &
                                    (city_vacay_df["Snow"] == 0)]

elif rain == "yes" and snow == "no":
    answer_filter_df = city_vacay_df.loc[(city_vacay_df["Max Temp"]<= max_temp) &
                                    (city_vacay_df["Max Temp"] >= min_temp) &
                                    (city_vacay_df["Rain/Inches"] == 0) &
                                    (city_vacay_df["Snow"] == 0)]

else:
    answer_filter_df = city_vacay_df.loc[(city_vacay_df["Max Temp"]<= max_temp) &
                                    (city_vacay_df["Max Temp"] >= min_temp) &
                                    (city_vacay_df["Rain/Inches"] == 0) &
                                    (city_vacay_df["Snow"] == 0)]

In [7]:
# Show table with city info matching rain/snow criteria
answer_filter_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
1,1,Nyaunglebin,MM,2020-04-19 19:35:51,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0
4,4,Rikitea,PF,2020-04-19 19:35:52,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0
6,6,Renala Khurd,PK,2020-04-19 19:35:53,30.88,73.60,75.52,37,19,4.41,few clouds,0.0,0.0
7,7,Kapaa,US,2020-04-19 19:35:53,22.08,-159.32,77.00,69,75,5.79,broken clouds,0.0,0.0
9,9,Sabang,ID,2020-04-19 19:35:54,5.89,95.32,83.03,74,31,6.96,scattered clouds,0.0,0.0

In [8]:
# Create dataframe based on desired climates
desired_travel_areas_df = answer_filter_df.dropna()
desired_travel_areas_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
1,1,Nyaunglebin,MM,2020-04-19 19:35:51,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0
4,4,Rikitea,PF,2020-04-19 19:35:52,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0
6,6,Renala Khurd,PK,2020-04-19 19:35:53,30.88,73.60,75.52,37,19,4.41,few clouds,0.0,0.0
7,7,Kapaa,US,2020-04-19 19:35:53,22.08,-159.32,77.00,69,75,5.79,broken clouds,0.0,0.0
9,9,Sabang,ID,2020-04-19 19:35:54,5.89,95.32,83.03,74,31,6.96,scattered clouds,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,Ibipeba,BR,2020-04-19 19:38:26,-11.64,-42.01,72.72,67,99,10.07,overcast clouds,0.0,0.0
603,603,Maua,BR,2020-04-19 19:35:00,-23.67,-46.46,71.60,68,40,14.99,scattered clouds,0.0,0.0
606,606,Gaspar,BR,2020-04-19 19:38:27,-26.93,-48.96,77.00,64,20,6.93,few clouds,0.0,0.0
608,608,Sur,OM,2020-04-19 19:38:27,22.57,59.53,84.36,52,0,7.16,clear sky,0.0,0.0
611,611,Nabire,ID,2020-04-19 19:38:28,-3.37,135.48,75.92,80,0,2.77,clear sky,0.0,0.0

In [9]:
desiredhotels_df = desired_travel_areas_df[["City", "Country","Max Temp","Lat","Lng"]].copy()
desiredhotels_df["Hotel Name"] = ""
desiredhotels_df

             City Country  Max Temp    Lat     Lng Hotel Name
1     Nyaunglebin      MM     74.21  17.95   96.73
4         Rikitea      PF     76.87 -23.12 -134.97
6    Renala Khurd      PK     75.52  30.88   73.60
7           Kapaa      US     77.00  22.08 -159.32
9          Sabang      ID     83.03   5.89   95.32
..            ...     ...       ...    ...     ...        ...
602       Ibipeba      BR     72.72 -11.64  -42.01
603          Maua      BR     71.60 -23.67  -46.46
606        Gaspar      BR     77.00 -26.93  -48.96
608           Sur      OM     84.36  22.57   59.53
611        Nabire      ID     75.92  -3.37  135.48

[224 rows x 6 columns]

In [11]:
# Set the parameters to search for a hotel example city.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

In [12]:
# Iterate through the DataFrame.
for index, row in desiredhotels_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

# Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

# Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   
# Grab the first hotel from the results and store the name.
    desiredhotels_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

# Grab the first hotel from the results and store the name.
    try:
        desiredhotels_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

IndexError: list index out of range

In [ ]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = desired_travel_areas[["Lat", "Lng"]]
max_temp = desired_travel_areas["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

In [ ]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPyPrac_vacay.csv"

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
##### Save and upload the new marker layer map as WeatherPy_vacation_map.png.

In [ ]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

In [ ]:
city_data_df.dtypes

In [ ]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [ ]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
    
# Assign the figure variable.
fig = gmaps.figure()

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

In [ ]:
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=2000, point_radius=20)
heat_layer

In [ ]:
fig

In [ ]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

In [ ]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

In [ ]:
# Heatmap of percent wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

In [ ]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [ ]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

In [ ]:
preferred_cities_df.count()

In [ ]:
preferred_cities_df.isnull().sum()

In [ ]:
preferred_cities_df.notnull().sum()

In [ ]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(177)

In [ ]:
#https://maps.googleapis.com/maps/api/place/nearbysearch/output?parameters

In [ ]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 10000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}

params["location"] = "22.29, 114.16"

# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
hotels

In [ ]:
#hotels["results"][0]

In [ ]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
   
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
   
  # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

In [ ]:
hotel_df.head(10)

In [ ]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

In [ ]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

In [ ]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""
fig

In [ ]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
fig

In [ ]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [ ]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig