## Module 6 Challenge
### Doris B. Cohen, April 2020 -------> Part 1

### Part 1 Instructions
Get the Weather Description and Amount of Precipitation for Each City
To complete this task, follow these steps:

1. Create a new Jupyter Notebook file and name it Weather_Database.ipynb.
2. Generate a new set of 1,500 random latitudes and longitudes.
3. Get the nearest city using the citipy module.
4. Perform an API call with the OpenWeatherMap.
5. Retrieve the following information from the API call:
    Latitude and longitude
    Maximum temperature
    Percent humidity
    Percent cloudiness
    Wind speed
    Weather description (e.g., clouds, fog, light rain, clear sky)
    Using a try-except block, in the try block if it is raining, get the amount of rainfall in inches for the last three hours. In the except block handle the KeyError if there is no rainfall and add 0 inches for the rainfall amount.
    Using a try-except block, in the try block if it is snowing, get the amount of snowfall in inches for the last three hours. In the except block handle the KeyError if there is no snowfall and add 0 inches for the snowfall amount.
6. Add the data to a new DataFrame.
7. Save the new DataFrame as a CSV file to be used for Part 2.
8. Upload the CSV file as part of your submission as WeatherPy_challenge.csv.
9. Answer this question using Pandas methods: How many cities have recorded rainfall or snow?

In [1]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
import scipy
import timeit
import requests
import traceback

# Import the commands and config info
import citipy
from citipy import citipy

from scipy import stats
from scipy.stats import linregress
from config import weather_api_key
from datetime import datetime

In [2]:
# Create a practice set of random latitude and longitude combinations.
x = [25.12903645, 25.92017388, 26.62509167, -59.98969384, 37.30571269]
y = [-67.59741259, 11.09532135, 74.84233102, -76.89176677, -61.13376282]
coordinates = zip(x, y)

In [3]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=1500)
lngs = np.random.uniform(low=-180.000, high=180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [4]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(coordinate[0], coordinate[1])

25.12903645 -67.59741259
25.92017388 11.09532135
26.62509167 74.84233102
-59.98969384 -76.89176677
37.30571269 -61.13376282

In [5]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [6]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

664

In [7]:
#https://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=439d4b804bc8187953eb36d2a8c26a02

# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [8]:
# Create an endpoint URL for a city.
city_url = url + "&q=" + "Boston"

In [9]:
# Make a 'Get' request for the city weather.
city_weather = requests.get(city_url)
city_weather

In [10]:
# Use this code in try/except statements, when necessary
#except:
     #traceback.print_exc()

In [11]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

Beginning Data Retrieval
-----------------------------

In [12]:
# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
    # Create endpoint URL with each city.
    city_url = url + "&q=" + city

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
    # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_weatherdesc = city_weather["weather"][0]["description"]
        try:
            #city_rain = city_weather["rain"]
            city_rain = city_weather["rain"]["3h"]
        except KeyError:
            city_rain = 0
        try:
            #city_snow = city_weather["snow"]
            city_snow = city_weather["snow"]["3h"]
        except KeyError:
            city_snow = 0
        city_country = city_weather["sys"]["country"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Weather Desc": city_weatherdesc,
                          "Rain/Inches": city_rain,
                          "Snow": city_snow,
                          "Country": city_country,
                          "Date": city_date})

    # If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Processing Record 1 of Set 1 | ustye
Processing Record 2 of Set 1 | nizhneyansk
City not found. Skipping...
Processing Record 3 of Set 1 | nyaunglebin
Processing Record 4 of Set 1 | verkhoyansk
Processing Record 5 of Set 1 | mataura
Processing Record 6 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 7 of Set 1 | babanusah
City not found. Skipping...
Processing Record 8 of Set 1 | rikitea
Processing Record 9 of Set 1 | tasiilaq
Processing Record 10 of Set 1 | bargal
City not found. Skipping...
Processing Record 11 of Set 1 | renala khurd
Processing Record 12 of Set 1 | kapaa
Processing Record 13 of Set 1 | mayo
Processing Record 14 of Set 1 | sabang
Processing Record 15 of Set 1 | atamanovka
Processing Record 16 of Set 1 | pisco
Processing Record 17 of Set 1 | guerrero negro
Processing Record 18 of Set 1 | puerto ayora
Processing Record 19 of Set 1 | albany
Processing Record 20 of Set 1 | jamestown
Processing Record 21 of Set 1 | sovetskiy
Processing Record 22 of Set 1 | gallup
Processing Record 23 of Set 1 | ahipara
Processing Record 24 of Set 1 | abu dhabi
Processing Record 25 of Set 1 | atuona
Processing Record 26 of Set 1 | dingle
Processing Record 27 of Set 1 | bluff
Processing Record 28 of Set 1 | vaini
Processing Record 29 of Set 1 | punta arenas
Processing Record 30 of Set 1 | nikolskoye
Processing Record 31 of Set 1 | ewo
Processing Record 32 of Set 1 | bathsheba
Processing Record 33 of Set 1 | atotonilco el grande
Processing Record 34 of Set 1 | hit
Processing Record 35 of Set 1 | toliary
City not found. Skipping...
Processing Record 36 of Set 1 | hithadhoo
Processing Record 37 of Set 1 | tuktoyaktuk
Processing Record 38 of Set 1 | novogurovskiy
Processing Record 39 of Set 1 | isangel
Processing Record 40 of Set 1 | khatanga
Processing Record 41 of Set 1 | soloneshnoye
Processing Record 42 of Set 1 | bethel
Processing Record 43 of Set 1 | busselton
Processing Record 44 of Set 1 | lengshuitan
Processing Record 45 of Set 1 | lillooet
Processing Record 46 of Set 1 | ilulissat
Processing Record 47 of Set 1 | phaltan
Processing Record 48 of Set 1 | avarua
Processing Record 49 of Set 1 | planadas
Processing Record 50 of Set 1 | port alfred
Processing Record 1 of Set 2 | hobart
Processing Record 2 of Set 2 | narsaq
Processing Record 3 of Set 2 | ushuaia
Processing Record 4 of Set 2 | katunino
Processing Record 5 of Set 2 | stepnyak
Processing Record 6 of Set 2 | chokurdakh
Processing Record 7 of Set 2 | enshi
Processing Record 8 of Set 2 | sidrolandia
Processing Record 9 of Set 2 | lebu
Processing Record 10 of Set 2 | beloha
Processing Record 11 of Set 2 | vanavara
Processing Record 12 of Set 2 | hermanus
Processing Record 13 of Set 2 | butaritari
Processing Record 14 of Set 2 | mar del plata
Processing Record 15 of Set 2 | menongue
Processing Record 16 of Set 2 | hamilton
Processing Record 17 of Set 2 | pallipattu
Processing Record 18 of Set 2 | severo-kurilsk
Processing Record 19 of Set 2 | biak
Processing Record 20 of Set 2 | hilo
Processing Record 21 of Set 2 | georgetown
Processing Record 22 of Set 2 | cape town
Processing Record 23 of Set 2 | chadan
Processing Record 24 of Set 2 | calbuco
Processing Record 25 of Set 2 | norman wells
Processing Record 26 of Set 2 | pawayan
Processing Record 27 of Set 2 | lagoa
Processing Record 28 of Set 2 | albanel
Processing Record 29 of Set 2 | banda aceh
Processing Record 30 of Set 2 | la ronge
Processing Record 31 of Set 2 | maun
Processing Record 32 of Set 2 | oktyabrskoye
Processing Record 33 of Set 2 | amapa
Processing Record 34 of Set 2 | abu samrah
Processing Record 35 of Set 2 | samalaeulu
City not found. Skipping...
Processing Record 36 of Set 2 | tiksi
Processing Record 37 of Set 2 | komsomolskiy
Processing Record 38 of Set 2 | valparaiso
Processing Record 39 of Set 2 | sorland
Processing Record 40 of Set 2 | codrington
Processing Record 41 of Set 2 | qaanaaq
Processing Record 42 of Set 2 | taltal
Processing Record 43 of Set 2 | mahebourg
Processing Record 44 of Set 2 | zelenoborskiy
Processing Record 45 of Set 2 | airai
Processing Record 46 of Set 2 | kiunga
Processing Record 47 of Set 2 | tautira
Processing Record 48 of Set 2 | leningradskiy
Processing Record 49 of Set 2 | tateyama
Processing Record 50 of Set 2 | maple creek
Processing Record 1 of Set 3 | cidreira
Processing Record 2 of Set 3 | itapirapua
Processing Record 3 of Set 3 | mehamn
Processing Record 4 of Set 3 | sorong
Processing Record 5 of Set 3 | mandalgovi
Processing Record 6 of Set 3 | raudeberg
Processing Record 7 of Set 3 | port elizabeth
Processing Record 8 of Set 3 | pitrufquen
Processing Record 9 of Set 3 | chegutu
Processing Record 10 of Set 3 | kurilsk
Processing Record 11 of Set 3 | quepos
Processing Record 12 of Set 3 | marzuq
Processing Record 13 of Set 3 | bogo
Processing Record 14 of Set 3 | crab hill
City not found. Skipping...
Processing Record 15 of Set 3 | castro
Processing Record 16 of Set 3 | belushya guba
City not found. Skipping...
Processing Record 17 of Set 3 | pierre
Processing Record 18 of Set 3 | porteirinha
Processing Record 19 of Set 3 | itarema
Processing Record 20 of Set 3 | fort nelson
Processing Record 21 of Set 3 | cherskiy
Processing Record 22 of Set 3 | la orilla
Processing Record 23 of Set 3 | esperance
Processing Record 24 of Set 3 | touros
Processing Record 25 of Set 3 | magole
Processing Record 26 of Set 3 | brae
Processing Record 27 of Set 3 | begoro
Processing Record 28 of Set 3 | torbay
Processing Record 29 of Set 3 | kaitangata
Processing Record 30 of Set 3 | fortuna
Processing Record 31 of Set 3 | sao filipe
Processing Record 32 of Set 3 | barrow
Processing Record 33 of Set 3 | kousseri
Processing Record 34 of Set 3 | samusu
City not found. Skipping...
Processing Record 35 of Set 3 | gilazi
City not found. Skipping...
Processing Record 36 of Set 3 | truth or consequences
Processing Record 37 of Set 3 | saskylakh
Processing Record 38 of Set 3 | juegang
Processing Record 39 of Set 3 | yabrud
Processing Record 40 of Set 3 | ribeira grande
Processing Record 41 of Set 3 | teahupoo
Processing Record 42 of Set 3 | nguiu
City not found. Skipping...
Processing Record 43 of Set 3 | takoradi
Processing Record 44 of Set 3 | george
Processing Record 45 of Set 3 | porto belo
Processing Record 46 of Set 3 | luderitz
Processing Record 47 of Set 3 | chaplynka
Processing Record 48 of Set 3 | iqaluit
Processing Record 49 of Set 3 | suileng
Processing Record 50 of Set 3 | bull savanna
Processing Record 1 of Set 4 | taolanaro
City not found. Skipping...
Processing Record 2 of Set 4 | karaul
City not found. Skipping...
Processing Record 3 of Set 4 | olafsvik
Processing Record 4 of Set 4 | haibowan
City not found. Skipping...
Processing Record 5 of Set 4 | luanda
Processing Record 6 of Set 4 | mursalimkino
Processing Record 7 of Set 4 | sibolga
Processing Record 8 of Set 4 | nome
Processing Record 9 of Set 4 | panama city
Processing Record 10 of Set 4 | puerto colombia
Processing Record 11 of Set 4 | bredasdorp
Processing Record 12 of Set 4 | chuy
Processing Record 13 of Set 4 | wentzville
Processing Record 14 of Set 4 | mirabad
Processing Record 15 of Set 4 | weihe
Processing Record 16 of Set 4 | sinkat
City not found. Skipping...
Processing Record 17 of Set 4 | mogadishu
Processing Record 18 of Set 4 | gornji milanovac
Processing Record 19 of Set 4 | cam ranh
Processing Record 20 of Set 4 | tual
Processing Record 21 of Set 4 | vardo
Processing Record 22 of Set 4 | san patricio
Processing Record 23 of Set 4 | kendari
Processing Record 24 of Set 4 | bela vista
Processing Record 25 of Set 4 | moshi
Processing Record 26 of Set 4 | dikson
Processing Record 27 of Set 4 | finote selam
Processing Record 28 of Set 4 | loralai
Processing Record 29 of Set 4 | broome
Processing Record 30 of Set 4 | bardiyah
Processing Record 31 of Set 4 | new norfolk
Processing Record 32 of Set 4 | mackay
Processing Record 33 of Set 4 | diffa
Processing Record 34 of Set 4 | jalu
Processing Record 35 of Set 4 | port hueneme
Processing Record 36 of Set 4 | daru
Processing Record 37 of Set 4 | kieta
Processing Record 38 of Set 4 | penaflor
Processing Record 39 of Set 4 | poum
Processing Record 40 of Set 4 | sedelnikovo

City not found. Skipping...
Processing Record 41 of Set 4 | mount gambier
Processing Record 42 of Set 4 | san cristobal
Processing Record 43 of Set 4 | wau
Processing Record 44 of Set 4 | gat
Processing Record 45 of Set 4 | thinadhoo
Processing Record 46 of Set 4 | cabo san lucas
Processing Record 47 of Set 4 | beaufort
Processing Record 48 of Set 4 | mys shmidta
City not found. Skipping...
Processing Record 49 of Set 4 | matara
Processing Record 50 of Set 4 | haines junction
Processing Record 1 of Set 5 | arlit
Processing Record 2 of Set 5 | natchitoches
Processing Record 3 of Set 5 | vaitupu
City not found. Skipping...
Processing Record 4 of Set 5 | masoko
Processing Record 5 of Set 5 | karratha
Processing Record 6 of Set 5 | halifax
Processing Record 7 of Set 5 | prachuap khiri khan
Processing Record 8 of Set 5 | viligili
City not found. Skipping...
Processing Record 9 of Set 5 | beyneu
Processing Record 10 of Set 5 | carnarvon
Processing Record 11 of Set 5 | souillac
Processing Record 12 of Set 5 | espanola
Processing Record 13 of Set 5 | camocim
Processing Record 14 of Set 5 | katghora
Processing Record 15 of Set 5 | baswa
Processing Record 16 of Set 5 | amderma
City not found. Skipping...
Processing Record 17 of Set 5 | barwadih
Processing Record 18 of Set 5 | los llanos de aridane
Processing Record 19 of Set 5 | cairns
Processing Record 20 of Set 5 | shimoda
Processing Record 21 of Set 5 | dole
Processing Record 22 of Set 5 | jamame
Processing Record 23 of Set 5 | la mana
Processing Record 24 of Set 5 | koslan
Processing Record 25 of Set 5 | sangueya
Processing Record 26 of Set 5 | buchanan
Processing Record 27 of Set 5 | vaitape
Processing Record 28 of Set 5 | north bay
Processing Record 29 of Set 5 | acajutiba
Processing Record 30 of Set 5 | kazalinsk
City not found. Skipping...
Processing Record 31 of Set 5 | ancud
Processing Record 32 of Set 5 | jinji
Processing Record 33 of Set 5 | san nicolas
Processing Record 34 of Set 5 | west bay
Processing Record 35 of Set 5 | tessalit
Processing Record 36 of Set 5 | boyolangu
Processing Record 37 of Set 5 | grindavik
Processing Record 38 of Set 5 | pringsewu
Processing Record 39 of Set 5 | lazaro cardenas
Processing Record 40 of Set 5 | kaka
Processing Record 41 of Set 5 | khandwa
Processing Record 42 of Set 5 | barpali
Processing Record 43 of Set 5 | wanning
Processing Record 44 of Set 5 | kruisfontein
Processing Record 45 of Set 5 | kulhudhuffushi
Processing Record 46 of Set 5 | gariaband
Processing Record 47 of Set 5 | wuxue
Processing Record 48 of Set 5 | bambous virieux
Processing Record 49 of Set 5 | mattru
Processing Record 50 of Set 5 | san jose
Processing Record 1 of Set 6 | egvekinot
Processing Record 2 of Set 6 | novyy urengoy
Processing Record 3 of Set 6 | coquimbo
Processing Record 4 of Set 6 | zhongshu
Processing Record 5 of Set 6 | grand-santi
Processing Record 6 of Set 6 | lashio
Processing Record 7 of Set 6 | nara
Processing Record 8 of Set 6 | san pedro
Processing Record 9 of Set 6 | aras
Processing Record 10 of Set 6 | severodvinsk
Processing Record 11 of Set 6 | klaksvik
Processing Record 12 of Set 6 | naze
Processing Record 13 of Set 6 | volchansk
Processing Record 14 of Set 6 | necochea
Processing Record 15 of Set 6 | verkhneyarkeyevo
Processing Record 16 of Set 6 | price
Processing Record 17 of Set 6 | arraial do cabo
Processing Record 18 of Set 6 | attawapiskat
City not found. Skipping...
Processing Record 19 of Set 6 | yellowknife
Processing Record 20 of Set 6 | hasaki
Processing Record 21 of Set 6 | northam
Processing Record 22 of Set 6 | cayenne
Processing Record 23 of Set 6 | cozumel
Processing Record 24 of Set 6 | hranice
Processing Record 25 of Set 6 | dalvik
Processing Record 26 of Set 6 | avera
Processing Record 27 of Set 6 | isla vista
Processing Record 28 of Set 6 | marysville
Processing Record 29 of Set 6 | saint anthony
Processing Record 30 of Set 6 | hochheim
Processing Record 31 of Set 6 | loreto
Processing Record 32 of Set 6 | babstovo
Processing Record 33 of Set 6 | east london
Processing Record 34 of Set 6 | faanui
Processing Record 35 of Set 6 | kavieng
Processing Record 36 of Set 6 | kigoma
Processing Record 37 of Set 6 | victoria
Processing Record 38 of Set 6 | palmer
Processing Record 39 of Set 6 | ostrovnoy
Processing Record 40 of Set 6 | clyde river
Processing Record 41 of Set 6 | burgdorf
Processing Record 42 of Set 6 | ovalle
Processing Record 43 of Set 6 | kikwit
Processing Record 44 of Set 6 | ucluelet
Processing Record 45 of Set 6 | cangzhou
Processing Record 46 of Set 6 | bushenyi
Processing Record 47 of Set 6 | san quintin
Processing Record 48 of Set 6 | thompson
Processing Record 49 of Set 6 | mitsamiouli
Processing Record 50 of Set 6 | do rud
City not found. Skipping...
Processing Record 1 of Set 7 | barentsburg
City not found. Skipping...
Processing Record 2 of Set 7 | honiara
Processing Record 3 of Set 7 | tevaitoa
Processing Record 4 of Set 7 | saint-philippe
Processing Record 5 of Set 7 | conneaut
Processing Record 6 of Set 7 | zamora
Processing Record 7 of Set 7 | afua
Processing Record 8 of Set 7 | smirnykh
Processing Record 9 of Set 7 | aflu
City not found. Skipping...
Processing Record 10 of Set 7 | luena
Processing Record 11 of Set 7 | longyearbyen
Processing Record 12 of Set 7 | srandakan
Processing Record 13 of Set 7 | porto novo
Processing Record 14 of Set 7 | ostersund
Processing Record 15 of Set 7 | chicama
Processing Record 16 of Set 7 | bonavista
Processing Record 17 of Set 7 | meadow lake
Processing Record 18 of Set 7 | shushenskoye
Processing Record 19 of Set 7 | morondava
Processing Record 20 of Set 7 | praia da vitoria
Processing Record 21 of Set 7 | agrado
Processing Record 22 of Set 7 | mazatlan
Processing Record 23 of Set 7 | grand river south east
City not found. Skipping...
Processing Record 24 of Set 7 | ponta do sol
Processing Record 25 of Set 7 | qandala
Processing Record 26 of Set 7 | longlac
City not found. Skipping...
Processing Record 27 of Set 7 | sakakah
Processing Record 28 of Set 7 | hurghada
Processing Record 29 of Set 7 | lata
Processing Record 30 of Set 7 | nizhniye sergi
Processing Record 31 of Set 7 | omsukchan
Processing Record 32 of Set 7 | dali
Processing Record 33 of Set 7 | barda
Processing Record 34 of Set 7 | antofagasta
Processing Record 35 of Set 7 | caravelas
Processing Record 36 of Set 7 | derzhavinsk
Processing Record 37 of Set 7 | piacabucu
Processing Record 38 of Set 7 | marsa matruh
Processing Record 39 of Set 7 | goderich
Processing Record 40 of Set 7 | ulaangom
Processing Record 41 of Set 7 | sao joao da barra
Processing Record 42 of Set 7 | eydhafushi
Processing Record 43 of Set 7 | safford
Processing Record 44 of Set 7 | makakilo city
Processing Record 45 of Set 7 | roald
Processing Record 46 of Set 7 | tuatapere
Processing Record 47 of Set 7 | wukari
Processing Record 48 of Set 7 | upernavik
Processing Record 49 of Set 7 | dillon
Processing Record 50 of Set 7 | andros town
Processing Record 1 of Set 8 | kapoeta
Processing Record 2 of Set 8 | vestmannaeyjar
Processing Record 3 of Set 8 | inhambane
Processing Record 4 of Set 8 | geraldton
Processing Record 5 of Set 8 | marienburg
Processing Record 6 of Set 8 | belaya gora
Processing Record 7 of Set 8 | chiesanuova
Processing Record 8 of Set 8 | lodwar
Processing Record 9 of Set 8 | kodiak
Processing Record 10 of Set 8 | zhezkazgan
Processing Record 11 of Set 8 | bonfim
Processing Record 12 of Set 8 | cowra
Processing Record 13 of Set 8 | mollendo
Processing Record 14 of Set 8 | college
Processing Record 15 of Set 8 | san vicente
Processing Record 16 of Set 8 | balkanabat
Processing Record 17 of Set 8 | angoche
Processing Record 18 of Set 8 | kochevo
Processing Record 19 of Set 8 | mecca
Processing Record 20 of Set 8 | yurga
Processing Record 21 of Set 8 | pevek
Processing Record 22 of Set 8 | sola
Processing Record 23 of Set 8 | villazon
Processing Record 24 of Set 8 | adela
Processing Record 25 of Set 8 | sehithwa
Processing Record 26 of Set 8 | provideniya
Processing Record 27 of Set 8 | talnakh
Processing Record 28 of Set 8 | imeni poliny osipenko
Processing Record 29 of Set 8 | panguna
Processing Record 30 of Set 8 | villa sandino

Processing Record 31 of Set 8 | bilma
Processing Record 32 of Set 8 | najran
Processing Record 33 of Set 8 | saldanha
Processing Record 34 of Set 8 | saint george
Processing Record 35 of Set 8 | balbriggan
Processing Record 36 of Set 8 | whitehorse
Processing Record 37 of Set 8 | devils lake
Processing Record 38 of Set 8 | north las vegas
Processing Record 39 of Set 8 | slonim
Processing Record 40 of Set 8 | mapiripan
Processing Record 41 of Set 8 | prince rupert
Processing Record 42 of Set 8 | tezu
Processing Record 43 of Set 8 | yulara
Processing Record 44 of Set 8 | port hardy
Processing Record 45 of Set 8 | portland
Processing Record 46 of Set 8 | nanortalik
Processing Record 47 of Set 8 | marcona
City not found. Skipping...
Processing Record 48 of Set 8 | henties bay
Processing Record 49 of Set 8 | aripuana
Processing Record 50 of Set 8 | watertown
Processing Record 1 of Set 9 | lahad datu
Processing Record 2 of Set 9 | tahta
Processing Record 3 of Set 9 | madingou
Processing Record 4 of Set 9 | lavrentiya
Processing Record 5 of Set 9 | demak
Processing Record 6 of Set 9 | solnechnyy
Processing Record 7 of Set 9 | flinders
Processing Record 8 of Set 9 | pandharpur
Processing Record 9 of Set 9 | sulangan
Processing Record 10 of Set 9 | mocuba
Processing Record 11 of Set 9 | kodinsk
Processing Record 12 of Set 9 | tsihombe
City not found. Skipping...
Processing Record 13 of Set 9 | bosilovo
Processing Record 14 of Set 9 | wajima
Processing Record 15 of Set 9 | asau
Processing Record 16 of Set 9 | orlik
Processing Record 17 of Set 9 | pundaguitan
Processing Record 18 of Set 9 | guadalupe victoria
Processing Record 19 of Set 9 | te anau
Processing Record 20 of Set 9 | suntar
Processing Record 21 of Set 9 | gizo
Processing Record 22 of Set 9 | grand gaube
Processing Record 23 of Set 9 | baykit
Processing Record 24 of Set 9 | atambua
Processing Record 25 of Set 9 | kanniyakumari
Processing Record 26 of Set 9 | dubti
Processing Record 27 of Set 9 | colares
Processing Record 28 of Set 9 | nhamunda
Processing Record 29 of Set 9 | ixtapa
Processing Record 30 of Set 9 | hami
Processing Record 31 of Set 9 | aranda de duero
Processing Record 32 of Set 9 | senneterre
Processing Record 33 of Set 9 | shelburne
Processing Record 34 of Set 9 | san joaquin
Processing Record 35 of Set 9 | beipiao
Processing Record 36 of Set 9 | nantucket
Processing Record 37 of Set 9 | linguere
Processing Record 38 of Set 9 | changji
Processing Record 39 of Set 9 | tomatlan
Processing Record 40 of Set 9 | palabuhanratu
City not found. Skipping...
Processing Record 41 of Set 9 | magadan
Processing Record 42 of Set 9 | copiapo
Processing Record 43 of Set 9 | tolaga bay
Processing Record 44 of Set 9 | laguna
Processing Record 45 of Set 9 | saint-joseph
Processing Record 46 of Set 9 | havre-saint-pierre
Processing Record 47 of Set 9 | malatya
Processing Record 48 of Set 9 | tubuala
Processing Record 49 of Set 9 | wasilla
Processing Record 50 of Set 9 | sentyabrskiy
City not found. Skipping...
Processing Record 1 of Set 10 | talara
Processing Record 2 of Set 10 | tadine
Processing Record 3 of Set 10 | elk city
Processing Record 4 of Set 10 | sitka
Processing Record 5 of Set 10 | katherine
Processing Record 6 of Set 10 | ossora
Processing Record 7 of Set 10 | tiarei
Processing Record 8 of Set 10 | puqi
Processing Record 9 of Set 10 | north bend
Processing Record 10 of Set 10 | salalah
Processing Record 11 of Set 10 | makubetsu
Processing Record 12 of Set 10 | wattegama
Processing Record 13 of Set 10 | santa cruz
Processing Record 14 of Set 10 | mazagao
Processing Record 15 of Set 10 | sibu
Processing Record 16 of Set 10 | port-gentil
Processing Record 17 of Set 10 | turukhansk
Processing Record 18 of Set 10 | ludvika
Processing Record 19 of Set 10 | oksfjord
Processing Record 20 of Set 10 | polyarnyy
Processing Record 21 of Set 10 | monte cristi
City not found. Skipping...
Processing Record 22 of Set 10 | ust-kamchatsk
City not found. Skipping...
Processing Record 23 of Set 10 | bengkulu
Processing Record 24 of Set 10 | marathokambos
City not found. Skipping...
Processing Record 25 of Set 10 | umzimvubu
City not found. Skipping...
Processing Record 26 of Set 10 | hambantota
Processing Record 27 of Set 10 | bubaque
Processing Record 28 of Set 10 | porangatu
Processing Record 29 of Set 10 | zhigansk
Processing Record 30 of Set 10 | nouadhibou
Processing Record 31 of Set 10 | kahului
Processing Record 32 of Set 10 | bakchar
Processing Record 33 of Set 10 | jiayuguan
Processing Record 34 of Set 10 | fairbanks
Processing Record 35 of Set 10 | qui nhon
Processing Record 36 of Set 10 | sumbawa
City not found. Skipping...
Processing Record 37 of Set 10 | diapaga
Processing Record 38 of Set 10 | les cayes
Processing Record 39 of Set 10 | pangnirtung
Processing Record 40 of Set 10 | sambava
Processing Record 41 of Set 10 | vanimo
Processing Record 42 of Set 10 | kimbe
Processing Record 43 of Set 10 | la libertad
Processing Record 44 of Set 10 | matay
Processing Record 45 of Set 10 | cap-aux-meules
Processing Record 46 of Set 10 | volsk
Processing Record 47 of Set 10 | kailua
Processing Record 48 of Set 10 | san juan
Processing Record 49 of Set 10 | boguchany
Processing Record 50 of Set 10 | harrisburg
Processing Record 1 of Set 11 | guilin
Processing Record 2 of Set 11 | rocha
Processing Record 3 of Set 11 | zhoucheng
Processing Record 4 of Set 11 | luwuk
Processing Record 5 of Set 11 | port macquarie
Processing Record 6 of Set 11 | kudahuvadhoo
Processing Record 7 of Set 11 | waddan
Processing Record 8 of Set 11 | lasa
Processing Record 9 of Set 11 | goure
Processing Record 10 of Set 11 | topolobampo
Processing Record 11 of Set 11 | cap malheureux
Processing Record 12 of Set 11 | dalbandin
Processing Record 13 of Set 11 | tiznit
Processing Record 14 of Set 11 | butte
Processing Record 15 of Set 11 | nhulunbuy
Processing Record 16 of Set 11 | blackfoot
Processing Record 17 of Set 11 | mogzon
Processing Record 18 of Set 11 | glinka
Processing Record 19 of Set 11 | cabedelo
Processing Record 20 of Set 11 | mahon
Processing Record 21 of Set 11 | san policarpo
Processing Record 22 of Set 11 | mastic beach
Processing Record 23 of Set 11 | labuhan
Processing Record 24 of Set 11 | imeni morozova
Processing Record 25 of Set 11 | arusha
Processing Record 26 of Set 11 | port blair
Processing Record 27 of Set 11 | jinchang
Processing Record 28 of Set 11 | aleksandrovskoye
Processing Record 29 of Set 11 | alihe
Processing Record 30 of Set 11 | zhanatas
City not found. Skipping...
Processing Record 31 of Set 11 | pandaria
Processing Record 32 of Set 11 | weligama
Processing Record 33 of Set 11 | outjo
Processing Record 34 of Set 11 | bako
Processing Record 35 of Set 11 | ybycui
Processing Record 36 of Set 11 | sioux lookout
Processing Record 37 of Set 11 | havoysund
Processing Record 38 of Set 11 | lucea
Processing Record 39 of Set 11 | balatonszabadi
Processing Record 40 of Set 11 | kourou
Processing Record 41 of Set 11 | dagua
Processing Record 42 of Set 11 | kuragino
Processing Record 43 of Set 11 | belmonte
Processing Record 44 of Set 11 | damietta
Processing Record 45 of Set 11 | nata
Processing Record 46 of Set 11 | muros
Processing Record 47 of Set 11 | hihifo
City not found. Skipping...
Processing Record 48 of Set 11 | manono
Processing Record 49 of Set 11 | west wendover
Processing Record 50 of Set 11 | ambilobe
Processing Record 1 of Set 12 | neiafu
Processing Record 2 of Set 12 | banes
Processing Record 3 of Set 12 | gijon
Processing Record 4 of Set 12 | ozgon
City not found. Skipping...
Processing Record 5 of Set 12 | cam pha
City not found. Skipping...
Processing Record 6 of Set 12 | saint-augustin
Processing Record 7 of Set 12 | kavaratti
Processing Record 8 of Set 12 | chimbarongo
Processing Record 9 of Set 12 | tazovskiy
Processing Record 10 of Set 12 | porto santo
Processing Record 11 of Set 12 | diu
Processing Record 12 of Set 12 | pyinmana
Processing Record 13 of Set 12 | superior
Processing Record 14 of Set 12 | katsuura
Processing Record 15 of Set 12 | korla
Processing Record 16 of Set 12 | baiyin
Processing Record 17 of Set 12 | carutapera
Processing Record 18 of Set 12 | tobermory

Processing Record 19 of Set 12 | winder
Processing Record 20 of Set 12 | skalistyy
City not found. Skipping...
Processing Record 21 of Set 12 | aykhal
Processing Record 22 of Set 12 | linhares
Processing Record 23 of Set 12 | soyo
Processing Record 24 of Set 12 | namatanai
Processing Record 25 of Set 12 | kathu
Processing Record 26 of Set 12 | port hedland
Processing Record 27 of Set 12 | old town
Processing Record 28 of Set 12 | hearst
Processing Record 29 of Set 12 | padang
Processing Record 30 of Set 12 | alice springs
Processing Record 31 of Set 12 | presidencia roque saenz pena
Processing Record 32 of Set 12 | gorin
Processing Record 33 of Set 12 | lukovetskiy
Processing Record 34 of Set 12 | port lincoln
Processing Record 35 of Set 12 | kameshkovo
Processing Record 36 of Set 12 | rawson
Processing Record 37 of Set 12 | kachikau
City not found. Skipping...
Processing Record 38 of Set 12 | xuddur
Processing Record 39 of Set 12 | fremont
Processing Record 40 of Set 12 | dengfeng
Processing Record 41 of Set 12 | oranjemund
Processing Record 42 of Set 12 | sept-iles
Processing Record 43 of Set 12 | lumberton
Processing Record 44 of Set 12 | jiangyou
Processing Record 45 of Set 12 | innoshima
Processing Record 46 of Set 12 | montalban
Processing Record 47 of Set 12 | chabahar
Processing Record 48 of Set 12 | tubruq
City not found. Skipping...
Processing Record 49 of Set 12 | margate
Processing Record 50 of Set 12 | warqla
City not found. Skipping...
Processing Record 1 of Set 13 | nichinan
Processing Record 2 of Set 13 | jacarau
Processing Record 3 of Set 13 | vostok
Processing Record 4 of Set 13 | martapura
Processing Record 5 of Set 13 | requena
Processing Record 6 of Set 13 | andenes
Processing Record 7 of Set 13 | harper
Processing Record 8 of Set 13 | namibe
Processing Record 9 of Set 13 | bangkalan
Processing Record 10 of Set 13 | kishtwar
Processing Record 11 of Set 13 | douala
Processing Record 12 of Set 13 | samarai
Processing Record 13 of Set 13 | aksay
Processing Record 14 of Set 13 | bouza
Processing Record 15 of Set 13 | banff
Processing Record 16 of Set 13 | cascais
Processing Record 17 of Set 13 | praia
Processing Record 18 of Set 13 | qasigiannguit
Processing Record 19 of Set 13 | ciudad bolivar
Processing Record 20 of Set 13 | buqayq
City not found. Skipping...
Processing Record 21 of Set 13 | bulolo
Processing Record 22 of Set 13 | katangli
Processing Record 23 of Set 13 | kamenskoye
City not found. Skipping...
Processing Record 24 of Set 13 | broken hill
Processing Record 25 of Set 13 | acarau
Processing Record 26 of Set 13 | glendive
Processing Record 27 of Set 13 | kazanskoye
Processing Record 28 of Set 13 | tyukalinsk
Processing Record 29 of Set 13 | peniche
Processing Record 30 of Set 13 | hommelvik
Processing Record 31 of Set 13 | eureka
Processing Record 32 of Set 13 | westport
Processing Record 33 of Set 13 | aksu
Processing Record 34 of Set 13 | eha amufu
Processing Record 35 of Set 13 | mpraeso
Processing Record 36 of Set 13 | imbituba
Processing Record 37 of Set 13 | inderborskiy
City not found. Skipping...
Processing Record 38 of Set 13 | kalmunai
Processing Record 39 of Set 13 | kaeo
Processing Record 40 of Set 13 | iquique
Processing Record 41 of Set 13 | visby
Processing Record 42 of Set 13 | husavik
Processing Record 43 of Set 13 | manoel urbano
Processing Record 44 of Set 13 | moose factory
Processing Record 45 of Set 13 | srednekolymsk
Processing Record 46 of Set 13 | cervo
Processing Record 47 of Set 13 | hastings
Processing Record 48 of Set 13 | berovo
Processing Record 49 of Set 13 | duldurga
Processing Record 50 of Set 13 | ibipeba
Processing Record 1 of Set 14 | maua
Processing Record 2 of Set 14 | ustupo
Processing Record 3 of Set 14 | kuche
City not found. Skipping...
Processing Record 4 of Set 14 | nouakchott
Processing Record 5 of Set 14 | gaspar
Processing Record 6 of Set 14 | kuvandyk
Processing Record 7 of Set 14 | sur
Processing Record 8 of Set 14 | richards bay
Processing Record 9 of Set 14 | tutoia
Processing Record 10 of Set 14 | nabire
Processing Record 11 of Set 14 | grants pass
Processing Record 12 of Set 14 | port hawkesbury
Processing Record 13 of Set 14 | iglesias
Processing Record 14 of Set 14 | chapayevka
-----------------------------
Data Retrieval Complete
-----------------------------

In [13]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow,Country,Date
0,Ustye,59.63,39.74,31.59,94,8,3.15,clear sky,0.0,0.0,RU,2020-04-19 19:35:51
1,Nyaunglebin,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0,MM,2020-04-19 19:35:51
2,Verkhoyansk,67.54,133.38,6.30,88,99,5.55,overcast clouds,0.0,0.0,RU,2020-04-19 19:35:51
3,Mataura,-46.19,168.86,44.01,80,95,5.99,overcast clouds,0.0,0.0,NZ,2020-04-19 19:35:52
4,Rikitea,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0,PF,2020-04-19 19:35:52

In [14]:
# Reorder column tables
new_column_order = ["City","Country","Date","Lat","Lng","Max Temp","Humidity","Cloudiness","Wind Speed","Weather Desc","Rain/Inches","Snow"]

In [15]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = city_data_df[new_column_order]
city_data_df

city_data_df = pd.DataFrame(city_data_df)
city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
0,Ustye,RU,2020-04-19 19:35:51,59.63,39.74,31.59,94,8,3.15,clear sky,0.0,0.0
1,Nyaunglebin,MM,2020-04-19 19:35:51,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0
2,Verkhoyansk,RU,2020-04-19 19:35:51,67.54,133.38,6.30,88,99,5.55,overcast clouds,0.0,0.0
3,Mataura,NZ,2020-04-19 19:35:52,-46.19,168.86,44.01,80,95,5.99,overcast clouds,0.0,0.0
4,Rikitea,PF,2020-04-19 19:35:52,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0
5,Tasiilaq,GL,2020-04-19 19:35:53,65.61,-37.64,33.80,64,98,9.17,overcast clouds,0.0,0.0
6,Renala Khurd,PK,2020-04-19 19:35:53,30.88,73.60,75.52,37,19,4.41,few clouds,0.0,0.0
7,Kapaa,US,2020-04-19 19:35:53,22.08,-159.32,77.00,69,75,5.79,broken clouds,0.0,0.0
8,Mayo,US,2020-04-19 19:32:10,38.89,-76.51,64.99,58,1,16.11,clear sky,0.0,0.0
9,Sabang,ID,2020-04-19 19:35:54,5.89,95.32,83.03,74,31,6.96,scattered clouds,0.0,0.0

In [17]:
# Create the output file (CSV).
output_data_file = "weather_data/WeatherPy.csv"

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")

In [18]:
city_weather_df = pd.read_csv("weather_data/WeatherPY.csv")
city_weather_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
0,0,Ustye,RU,2020-04-19 19:35:51,59.63,39.74,31.59,94,8,3.15,clear sky,0.0,0.0
1,1,Nyaunglebin,MM,2020-04-19 19:35:51,17.95,96.73,74.21,72,35,3.67,scattered clouds,0.0,0.0
2,2,Verkhoyansk,RU,2020-04-19 19:35:51,67.54,133.38,6.30,88,99,5.55,overcast clouds,0.0,0.0
3,3,Mataura,NZ,2020-04-19 19:35:52,-46.19,168.86,44.01,80,95,5.99,overcast clouds,0.0,0.0
4,4,Rikitea,PF,2020-04-19 19:35:52,-23.12,-134.97,76.87,68,100,6.96,overcast clouds,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,611,Nabire,ID,2020-04-19 19:38:28,-3.37,135.48,75.92,80,0,2.77,clear sky,0.0,0.0
612,612,Grants Pass,US,2020-04-19 19:38:28,42.44,-123.33,63.00,47,1,0.92,clear sky,0.0,0.0
613,613,Port Hawkesbury,CA,2020-04-19 19:38:28,45.62,-61.35,36.00,80,90,21.92,moderate rain,0.0,0.0
614,614,Iglesias,IT,2020-04-19 19:38:29,39.31,8.54,64.99,88,75,6.93,broken clouds,0.0,0.0
615,615,Chapayevka,UA,2020-04-19 19:38:29,47.47,36.35,47.84,69,100,5.91,overcast clouds,0.0,0.0

In [37]:
#9 (Answer this question using Pandas methods): How many cities have recorded rainfall or snow?
rain_df = pd.DataFrame(city_weather_df, columns = ["Rain/Inches"])

In [38]:
#9 (Answer this question using Pandas methods): How many cities have recorded rainfall or snow?
snow_df = pd.DataFrame(city_weather_df, columns = ["Snow"])

In [39]:
#9 (Answer this question using Pandas methods): How many cities have recorded rainfall or snow?
#rainsnow_df = pd.DataFrame(city_weather_df, columns = ["Rain/Inches","Snow"])

In [40]:
# Snow inches info
snow_df

     Snow
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
..    ...
611   0.0
612   0.0
613   0.0
614   0.0
615   0.0

[616 rows x 1 columns]

In [41]:
# Rain inches info
rain_df

     Rain/Inches
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
..           ...
611          0.0
612          0.0
613          0.0
614          0.0
615          0.0

[616 rows x 1 columns]

In [44]:
# Count of snow column
snow_df["Snow"].count()

616

In [50]:
# Rain by inches
raincities_df = pd.read_csv("weather_data/raincities.csv")
raincities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
0,51,Enshi,CN,4/19/2020 19:36,30.30,109.48,60.57,73,93,1.88,moderate rain,9.95,0
1,384,Wajima,JP,4/19/2020 19:37,37.40,136.90,51.66,93,100,18.86,moderate rain,8.79,0
2,235,Nara,JP,4/19/2020 19:36,34.69,135.80,55.99,86,100,11.21,moderate rain,7.89,0
3,233,Grand-Santi,GF,4/19/2020 19:36,4.25,-54.38,78.35,92,100,3.51,moderate rain,5.42,0
4,560,Requena,ES,4/19/2020 19:38,39.49,-1.10,60.01,89,100,4.92,moderate rain,5.39,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,604,Ustupo,PA,4/19/2020 19:38,9.13,-77.93,84.97,65,51,4.59,light rain,0.13,0
87,286,Srandakan,ID,4/19/2020 19:37,-7.94,110.25,78.80,81,99,2.37,light rain,0.12,0
88,537,Padang,ID,4/19/2020 19:38,-0.95,100.35,78.03,77,7,3.89,light rain,0.12,0
89,467,Luwuk,ID,4/19/2020 19:37,-0.95,122.79,80.31,71,13,4.09,light rain,0.11,0
90,491,Aleksandrovskoye,RU,4/19/2020 19:37,44.71,43.00,59.00,58,62,6.71,light rain,0.11,0

In [51]:
# Snow by inches
snowcities_df = pd.read_csv("weather_data/snowcities.csv")
snowcities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Desc,Rain/Inches,Snow
0,290,Bonavista,CA,4/19/2020 19:32,48.65,-53.11,31.30,97,100,37.29,snow,0,3.85
1,348,Provideniya,RU,4/19/2020 19:37,64.38,-173.30,20.62,95,100,15.48,light snow,0,0.38
2,343,Pevek,RU,4/19/2020 19:35,69.70,170.31,6.94,94,100,5.23,light snow,0,0.21
3,350,Imeni Poliny Osipenko,RU,4/19/2020 19:37,52.42,136.49,23.61,94,100,18.92,light snow,0,0.16
4,112,Cherskiy,RU,4/19/2020 19:36,68.75,161.30,4.10,93,99,6.98,light snow,0,0.13
5,536,Hearst,CA,4/19/2020 19:36,49.68,-83.67,23.45,87,100,6.49,light snow,0,0.13